services:
  app:
    image: golang:1.22.5-alpine3.20
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    # environment:
      # - DATABASE_URL=postgres://app:pass@db/short

  db:
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=gophermart
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  db-accrual:
    image: postgres:16.2-alpine3.19
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=accrual
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
